README.md
client/package-lock.json
client/package.json
docker-compose.yml
server/package-lock.json
server/package.json

- Fix typo in README
- Update Plaid node bindings package version to ^4.0.0

Update to 1.0.1

---

Makefile
README.md
client/package-lock.json
client/package.json
client/src/components/Banner.jsx
client/src/components/LinkButton.jsx
client/src/components/MoreDetails.jsx
client/src/hooks/index.js
client/src/hooks/useOnClickOutside.js
docker-compose.yml
server/README.md
server/package-lock.json
server/package.json
version.sh
wait-for-client.sh

- Add "Beta" to README header for clarity
- Fixed a client bug that caused the buttons in dropdown elements to not accept click events if the item was the last element in a list
- Other smalls nits and cleanups

update to 1.0.2

---

README.md

Adds instructions to help Windows users get Pattern up and running.

Update README to provide a link to WSL instructions

---

client/src/components/ItemList.jsx
client/src/components/UserCard.jsx

add Link component from Router to navigation link and touchable in the usercard

change to use router link component

---

README.md

Updates README to include OAuth redirect URI.

add redirect uri language to readme

---

.gitignore
client/src/App.scss
client/src/components/NetWorth.tsx
client/src/services/api.tsx
client/src/services/assets.tsx
server/db/queries/assets.js
server/db/queries/index.js
server/routes/assets.js

add ability to delete a personal asset

add deletion of assets capability

---

client/src/components/CategoriesChart.tsx

Add dollar signs to pie chart labels

Lw add dollar sign to pie chart

---

client/package-lock.json
client/package.json
client/src/App.scss
client/src/components/ItemCard.tsx
client/src/components/LoadingCallout.tsx
client/src/components/NetWorth.tsx
client/src/components/UserPage.tsx
client/src/components/index.ts
server/routes/linkTokens.js

1) add loading component from threads while waiting for transactions webhooks on first item add so that it does not show $0.00 explicitly -   also adds callout and explanation in case webhooks are not received.
2) add call out when there are no transactions when the item is clicked. 
3) add persistence to personal assets so that they render even after all of a user's bank items have been removed.

Lw loading

---

client/src/components/Asset.tsx
client/src/components/UserPage.tsx

1) adds 2 decimal places to amounts
2) clears form when modal is submitted
3) makes fields required

Lw fix add asset modal

---

client/src/App.scss
client/src/components/ItemCard.tsx

remove bankId

---

server/plaid.js

fixes error response to reflect updated clibs

update error response to reflect updated clibs

---

client/src/App.scss
client/src/App.tsx
client/src/components/ErrorMessage.tsx
client/src/components/LinkButton.tsx
client/src/components/UserPage.tsx
client/src/components/index.ts
client/src/services/errors.tsx
client/src/services/index.js
client/src/util/index.tsx

1) Adds ErrorMessage component to display link errors: messages to end-user are based on particular errors.  
2) Adds errors context to provide error data to other components

add error context and component

---

server/routes/linkTokens.js

remove console.log

---

server/routes/linkTokens.js

check for redirect URI for OAuth

---

client/package-lock.json
client/package.json
client/src/components/ItemCard.tsx
server/package-lock.json
server/package.json

update clibs to 9.3.0

---

client/src/components/Banner.tsx

change to "How do you like this app?"

change language on feedback button

---

client/package-lock.json
client/package.json

fix critical and high vulnerabilities

fix vulnerabilities

---

README.md

add language to readme for pattern.plaid.com

add pattern hosted language

---

README.md
client/src/components/Sockets.jsx
database/init/create.sql
server/db/queries/index.js
server/db/queries/items.js
server/db/queries/transactions.js
server/package-lock.json
server/package.json
server/plaid.js
server/routes/items.js
server/update_transactions.js
server/webhookHandlers/handleTransactionsWebhook.js

Co-authored-by: Linda Woo <77688518+lindawoo-plaid@users.noreply.github.com>

Move example code to use sync api

---

ngrok/Dockerfile

Fixes https://github.com/plaid/pattern/issues/308 by creating conditional logic for download URL

Adh fix 308
